# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExampleProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
#pod 'PurchasePopUp', :path => '../'

pod 'PurchasePopUp'


end
